---
- name: Add repo file
  template: src=mariadb_centos.repo.j2 dest=/etc/yum.repos.d/mariadb.repo owner=root group=root mode=0644
  when: ansible_distribution == "CentOS"

- name: Add repo file
  template: src=mariadb_redhat.repo.j2 dest=/etc/yum.repos.d/mariadb.repo owner=root group=root mode=0644
  when: ansible_distribution == "RedHat"

- name: Install MariaDB
  yum: name={{ item }} enablerepo=mariadb state=present
  with_items:
    - MariaDB-server
    - MariaDB-client

- name: Install MySQLdb Python package for secure installations.
  yum: name=MySQL-python state=present
  when: mysql_secure_installation and mysql_root_password is defined
