---
- name: Add repo file
  template:
    src: "mariadb_centos.repo.j2"
    dest: "/etc/yum.repos.d/mariadb.repo"
    owner: "root"
    group: "root"
    mode: "0644"

- name: Install MariaDB
  yum: name={{ item }} enablerepo=mariadb state=present
  with_items:
    - MariaDB-server
    - MariaDB-client

- name: Install MySQLdb Python package for secure installations.
  yum: name=MySQL-python state=present

- name: "Update the server.cnf"
  template:
    src: "centos_server.cnf.j2"
    dest: "/etc/my.cnf.d/server.cnf"
    owner: "root"
    mode: "0644"

  notify:
    - "restart mysql"

- name: "Update the client.cnf"
  template:
    src: "centos_client.cnf.j2"
    dest: "/etc/my.cnf.d/client.cnf"
    owner: "root"
    mode: "0644"

  notify:
    - "restart mysql"
